In [1]:
import pandas as pd
import numpy as np


In [4]:
data = pd.read_csv("Downloads\dataNb.csv")
data

WC  W3  0U  W1    WM
0    0   3   0   0     N
1    0   3   0   1     N
2    1   3   0   0     Y
3    2   2   0   0     Y
4    2   1   1   0     Y
5    2   1   1   1     N
6    1   1   1   1     Y
7    0   2   0   0     N
8    0   1   1   0     Y
9    2   2   1   0     Y
10   0   2   1   1     Y
11   1   2   0   1     Y
12   1   3   1   0     Y
13   2   2   0   1     N
14   0   2   1   1  Null

In [56]:
X = data.iloc[:,:-1].values
y = data.iloc[:,4].values
print(X)

[[0 3 0 0]
 [0 3 0 1]
 [1 3 0 0]
 [2 2 0 0]
 [2 1 1 0]
 [2 1 1 1]
 [1 1 1 1]
 [0 2 0 0]
 [0 1 1 0]
 [2 2 1 0]
 [0 2 1 1]
 [1 2 0 1]
 [1 3 1 0]
 [2 2 0 1]
 [0 2 1 1]]


In [59]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
y_pred

array(['Y', 'Y', 'Y', 'N', 'Null', 'Y'], dtype='<U4')

In [60]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred)*100)



50.0


NameError: name 'y_pred' is not defined